version: '3.8'
services:
  nginx:
    image: nginx:mainline-alpine
    restart: always
    hostname: commune.local
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - ./.nginx:/etc/nginx/conf.d
      - ./.certs:/etc/ssl/certs
      - ./astro/dist:/astro
  db:
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./.db:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
volumes:
  db:
    driver: local
  nginx:
    driver: local
  certs:
    driver: local
